project_path: .
data_path: data/exchange_rate.txt
read_format: csv
write_format: parquet
selected_columns: ["Australia", "British", "Canada", "Switzerland", "China", "Japan", "NewZealand", "Singapore"] # should include all target column, can include additional columns
target_columns: ["Australia", "British", "Canada", "Switzerland", "China", "Japan", "NewZealand", "Singapore"]
return_targets: true

group_proportions:
- 0.8
- 0.1
- 0.1
seq_length: 200
max_rows: null