project_path: .
model_name: default4
read_format: parquet
ddconfig_path: configs/ddconfigs/exchange_rate.json

selected_columns: ["Australia", "British", "Canada", "Switzerland", "China", "Japan", "NewZealand", "Singapore"] # should include all target column, can include additional columns
target_columns: ["Australia", "British", "Canada", "Switzerland", "China", "Japan", "NewZealand", "Singapore"]
target_column_types: # 'criterion' in training_spec must also be adapted
  Australia: real
  British: real
  Canada: real
  Switzerland: real
  China: real
  Japan: real
  NewZealand: real
  Singapore: real

seq_length: 1000
inference_batch_size: 1

export_onnx: true
export_pt: true

model_spec:
  d_model: 64
  nhead: 12
  d_hid: 64
  nlayers: 5
training_spec:
  device: cuda
  epochs: 50
  iter_save: 5
  batch_size: 16
  log_interval: 10
  lr: 0.001
  accumulation_steps: 1
  dropout: 0.1
  criterion:
    Australia: MSELoss
    British: MSELoss
    Canada: MSELoss
    Switzerland: MSELoss
    China: MSELoss
    Japan: MSELoss
    NewZealand: MSELoss
    Singapore: MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: LinearLR
    start_factor: 1.0
    end_factor: 0.1
    total_iters: 50
  continue_training: true